version: '3.4'

services:
  app:
    container_name: testerv.app
    environment:
        - APACHE_DOCUMENT_ROOT=/var/www/html/public
        - REDIS_URL=redis://cache
    ports: 
        - 80:80
    build: 
        context: .
    volumes:
        - .:/var/www/html
        - ./docker/config/vhost.conf:/etc/apache2/sites-available/000-default.conf
        - ./docker/config/my.cnf:/etc/my.cnf
    links:
      - redis

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379

