version: '3.4'

services:
  app:
    container_name: testerv.app
    environment:
        - APACHE_DOCUMENT_ROOT=/var/www/html/public
    ports: 
        - 80:80
    build: 
        context: .
    volumes:
        - .:/var/www/html
        - ./docker/config/vhost.conf:/etc/apache2/sites-available/000-default.conf
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zaq1@WSX

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

