version: '3.4'

services:
  app:
    container_name: testerv.app
    environment:
        - APACHE_DOCUMENT_ROOT=/var/www/html/public
    ports: 
        - 80:80
    build: 
        context: .
    volumes:
        - .:/var/www/html
        - ./docker/config/vhost.conf:/etc/apache2/sites-available/000-default.conf

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

