System\Domain\User:
  type: entity
  table: user
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields: ~
  embedded:
    email:
      class: App\Domain\User\Email
    username:
      class: App\Domain\User\Username